# Generated by Django 2.0.1 on 2018-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogramme',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
