# Generated by Django 2.0.1 on 2018-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attended_courses',
            field=models.ManyToManyField(related_name='attended_courses', to='courses.Course'),
        ),
    ]
