# Generated by Django 2.0.1 on 2018-01-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_student_attended_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attended_courses',
        ),
    ]
