# Generated by Django 2.0.1 on 2018-02-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180221_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='studyprogramme',
            old_name='study_programme_slug',
            new_name='slug',
        ),
    ]
