# Generated by Django 2.0.1 on 2018-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180221_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_category',
            field=models.CharField(choices=[('Course', 'Course'), ('Seminar', 'Seminar')], default='Course', max_length=2),
        ),
    ]
