# Generated by Django 2.0.1 on 2018-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180222_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_category',
            field=models.CharField(choices=[('Course', 'Course'), ('Seminar', 'Seminar')], default='Course', max_length=10),
        ),
    ]
