# Generated by Django 2.0.1 on 2018-02-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180222_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_category',
            field=models.CharField(blank=True, choices=[('Courses', 'Courses'), ('Seminars', 'Seminars')], default='Courses', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
