# Generated by Django 2.0.1 on 2018-02-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180222_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
