# Generated by Django 2.0.1 on 2018-02-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180226_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enroll_slug',
        ),
    ]
