# Generated by Django 2.0.1 on 2018-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_enroll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
