# Generated by Django 2.0.1 on 2018-02-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_studentdata_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
