# Generated by Django 2.0.1 on 2018-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_studentdata_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='course',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='courses.Course'),
        ),
    ]
