# Generated by Django 2.0.1 on 2018-02-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20180226_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(default=None, to='courses.StudentData'),
        ),
    ]
