# Generated by Django 2.0.1 on 2018-02-27 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20180227_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
