# Generated by Django 2.0.1 on 2018-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20180227_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=None, null=True),
        ),
    ]
