# Generated by Django 2.0.1 on 2018-02-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20180227_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_course_teacher', to='courses.TeacherData', verbose_name='Course Teacher'),
        ),
    ]
