# Generated by Django 2.0.1 on 2018-02-28 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20180227_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_programme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.StudyProgramme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_course_teacher', to='courses.TeacherData', verbose_name='Course Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
