# Generated by Django 2.0.1 on 2018-02-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_notification_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='notification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Notification'),
        ),
    ]
