# Generated by Django 2.0.1 on 2018-02-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20180228_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
