# Generated by Django 2.0.1 on 2018-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20180228_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='student_files')),
                ('course', models.ForeignKey(default=None, on_delete=None, related_name='files', to='courses.Course')),
            ],
        ),
    ]
