# Generated by Django 2.0.1 on 2018-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_studentfileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfileupload',
            name='course',
        ),
        migrations.AddField(
            model_name='studentfileupload',
            name='student',
            field=models.ForeignKey(default=None, on_delete=None, related_name='files', to='courses.Student'),
        ),
    ]
