# Generated by Django 2.0.1 on 2018-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20180302_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfileupload',
            name='student',
        ),
        migrations.AddField(
            model_name='studentfileupload',
            name='course',
            field=models.ForeignKey(default=None, on_delete=None, related_name='files', to='courses.Course'),
        ),
    ]
