# Generated by Django 2.0.1 on 2018-03-02 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20180302_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfileupload',
            name='user',
            field=models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
