# Generated by Django 2.0.1 on 2018-03-02 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_studentfileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfileupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
