# Generated by Django 2.0.1 on 2018-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20180302_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfileupload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
