# Generated by Django 2.0.1 on 2018-03-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20180302_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfileupload',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Student'),
        ),
    ]
