# Generated by Django 2.0.1 on 2018-03-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20180302_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfileupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentfileupload',
            name='user',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.Student'),
        ),
    ]
