# Generated by Django 2.0.1 on 2018-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20180302_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfileupload',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='file_status',
            field=models.BooleanField(default=False),
        ),
    ]
