# Generated by Django 2.0.1 on 2018-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20180305_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='course',
        ),
        migrations.AddField(
            model_name='studentfileupload',
            name='show_again',
            field=models.BooleanField(default=False),
        ),
    ]
