# Generated by Django 2.0.1 on 2018-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_studentfileupload_show_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_upload',
            field=models.BooleanField(default=False),
        ),
    ]
