# Generated by Django 2.0.1 on 2018-03-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_course_allow_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='website',
        ),
    ]
