# Generated by Django 2.0.1 on 2018-03-18 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_remove_teacher_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.StudyProgramme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_course_teacher', to='courses.TeacherData', verbose_name='Course Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_seminar_teacher', to='courses.TeacherData', verbose_name='Seminar Teacher'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=None, related_name='files', to='courses.Lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Not a valid phone number.', regex='^[a-zA-Z0-9+]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='students_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(blank=True, default='', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='The ID needs to be 14 characters long.', regex='^.{14}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentfileupload',
            name='course',
            field=models.ForeignKey(null=True, on_delete=None, related_name='files', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='studentfileupload',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyprogramme',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='biography',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='teacher_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_ID',
            field=models.CharField(blank=True, default='', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='The ID needs to be 14 characters long.', regex='^.{14}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        # migrations.DeleteModel(
        #     name='Control',
        # ),
    ]
