# Generated by Django 2.0.1 on 2018-03-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20180318_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Control',
        ),
    ]
