# Generated by Django 2.0.1 on 2018-03-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_auto_20180319_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='files',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
