# Generated by Django 2.0.3 on 2018-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_studentuser_teacheruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'teacher')], default=0),
        ),
    ]
