# Generated by Django 2.0.3 on 2018-03-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
