# Generated by Django 2.0.3 on 2018-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20180322_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'teacher'), (2, 'admin')], default=2),
        ),
    ]
